# defaults - https://alacritty.org/config-alacritty-bindings.html
# see example.toml

[general]
live_config_reload = true
[env]
[window]
startup_mode = "Maximized"
opacity = 0.95
[scrolling]
[font]
size = 16
[colors]
[bell]
duration = 0
[selection]
save_to_clipboard = true
[cursor]
[terminal]
[mouse]
[hints]
[keyboard]
bindings = [
    { key = "C", mods = "Alt", action = "ToggleViMode" },
    { key = "Q", mode = "Vi", action = "ToggleViMode" },
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
[debug]
